FROM node:16 AS builder

# Createa app directory
WORKDIR /app

# A wildcard is used to ensure both package.json and package-lock.json are copied
COPY package*.json ./
COPY prisma ./prisma/

# install app dependencies contained in the package.json
RUN npm install

COPY . .

EXPOSE 3000
CMD [ "npm", "run", "migrate"; "npm", "run", "start" ]